Add: shooter_scoreを元にresultへの遷移
claustra01/virtual-natsumatsuri-frontend pull request #46
Opened 2024-08-17 06:12 UTC by Sea10wood

2024-08-17 08:11 UTC, K-Kizuku requested changes

2024-08-17 08:11 UTC, K-Kizuku commented on src/App.tsx
> +	const [score, setScore] = useState(0);
zustundの方で値を管理するようにしてもらえると
(これだとscoreの値が変わるたびに全体が再レンダリングされてしまうので)

2024-08-17 08:11 UTC, K-Kizuku commented on src/pages/result/index.tsx
> +					href={`https://twitter.com/intent/tweet?text=Webの射的で遊んだよ。${score}本倒した！%20%23virtualnatsumatsuri`}
ハックツの夏祭りように改修してるので、
`#ハックツ夏祭り`
のハッシュハグつけるようにしてもらえると

2024-08-17 08:11 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> +				setScoreState(newScore);
```suggestion
				setScoreState((prev) => prev + 1);
```
こんな感じで値の更新をしないと正しくstateが更新されない場合があるので、変更お願いします

2024-08-17 08:11 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> +			setScore(score);
この処理の意味を教えてください

2024-08-17 08:13 UTC, claustra01 commented on src/App.tsx
> +	const [score, setScore] = useState(0);
ごめんこれ僕の実装ですね
一緒に直しておいてください

2024-08-18 08:50 UTC, Sea10wood commented on src/pages/shooter/index.tsx
> +			setScore(score);
これは、images(コルクの残量)が0になったときにresultに遷移する処理です！

2024-08-18 15:37 UTC, K-Kizuku requested changes

2024-08-18 15:37 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> +				setScore((prevScore: number) => prevScore + 1);
```suggestion
				addOneScore();
```

2024-08-18 15:37 UTC, K-Kizuku commented on src/store/useScoreStore.ts
> +import create from "zustand";
```suggestion
import create from "zustand";

type State = {
  score: number;
};

type Action = {
  setScore: (score: number) => void;
  addOneScore: () => void;
};

export const useScoreStore = create<State & Action>()((set) => ({
  score: 0,
  setScore: (score) => set(() => ({ score: score })),
  addOneScore: () => set((state) => ({ score: state.score + 1 })),
}));
```
実装なんかキモくね？

2024-08-18 15:37 UTC, K-Kizuku commented on src/pages/result/index.tsx
> +	const image = images[score] || images[0];
```suggestion
	const image = `/drink/bottle${score}.webp`
```
このほうが綺麗じゃね？
あと、`images[score]`がnullになる場合ってある？
(それよりはscoreがimagesのlengthを越えてないかのチェックとかの方があった方がいい気がする)

2024-08-18 16:25 UTC, Sea10wood commented on src/pages/result/index.tsx
> +	const image = images[score] || images[0];
確かに,scoreがimagesのlengthを越えてないかのチェックの方がいいですね、、書き換えました！

2024-08-18 16:45 UTC, K-Kizuku approved these changes

2024-08-18 16:45 UTC, merged