ぬるぬる動くようになった
claustra01/virtual-natsumatsuri-frontend pull request #49
Opened 2024-08-17 22:30 UTC by K-Kizuku

2024-08-17 22:48 UTC, Sea10wood approved these changes, later dismissed
jaとLinkの閉じかっこの修正、諸々あざます。

2024-08-18 00:43 UTC, claustra01 requested changes
なんかrebaseミスってるぽい

2024-08-18 00:43 UTC, claustra01 commented on src/components/Yatai/TargetOverlay.tsx
> -		// setTarget({ x, y });
この辺、pointerはaimで、actionはtargetでx,yを保持していようという意図の宣言だったんですけど、よく考えたら別にaimだけで良さそうですね
であれば、aimTargetとshotTargetも統合できるので、不要なコメント群諸々綺麗にして欲しいです

2024-08-18 00:43 UTC, claustra01 commented on index.html
> +<!DOCTYPE html>
これ大文字か小文字に統一できません？？

2024-08-18 00:43 UTC, claustra01 commented on src/pages/shooter/index.tsx
> -	const [score, setScore] = useState<number>(0);
このscoreは命中した数のカウント用なんだ！！消さないでくれ🥺🥺

2024-08-18 00:43 UTC, claustra01 commented on src/pages/shooter/index.tsx
> -	}, [onMessage, uuid, score]);
この辺でtype=hitのwebsocketメッセージを受け取ってスコアをカウントしてる
消さないでくれ🥺🥺

2024-08-18 00:43 UTC, claustra01 commented on src/components/Yatai/TargetOverlay.module.css
> +  transition: all 0.1s linear;
このtransitionは何のためのもの？

2024-08-18 00:43 UTC, claustra01 commented on src/pages/shooter/index.tsx
> +			console.log(event.alpha, event.beta, event.gamma);
console.log消したい

2024-08-18 00:43 UTC, claustra01 commented on src/pages/shooter/index.tsx
> +					: event.beta,
これはどういう計算式なのか説明お願いします

2024-08-18 07:08 UTC, K-Kizuku commented on src/components/Yatai/TargetOverlay.tsx
> -		// setTarget({ x, y });
あーこの使い分け意味あるのかと思ったけど統合していいやつなのね
統合しときます

2024-08-18 07:10 UTC, K-Kizuku commented on index.html
> +<!DOCTYPE html>
これリンターがこうしてるんだよね
だからそれが適切なのかなという
(プロジェクトの設定にはないやつでワイのローカルのやつなので気になるなら統一してもいいけど、linterの方が正しいんじゃねと思ってる)

2024-08-18 07:10 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> -	const [score, setScore] = useState<number>(0);
あ、ミスって消してたわ
戻しとく

2024-08-18 07:11 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> -	}, [onMessage, uuid, score]);
同じく戻しとく

2024-08-18 07:13 UTC, K-Kizuku commented on src/components/Yatai/TargetOverlay.module.css
> +  transition: all 0.1s linear;
cssアニメーション
100msおきにしかターゲットの座標が更新されないのをその間をcssアニメーションで補完してる感じ
具体的にいうと、topとかleftの値の変更を0.1sかけて一定の速度で滑らかに動かしてる感じ

2024-08-18 07:13 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> +			console.log(event.alpha, event.beta, event.gamma);
うぃ

2024-08-18 07:17 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> +					: event.beta,
gammaのところに関してかな？
gammaの移動量が小さかったので2倍にした(gammaだけ-90~90の値の変更で他と比べて小さい)
他の部分に関してはinitialOrientationに値があればその差分、なければその値をそのまま返すようにしている

2024-08-18 07:47 UTC, claustra01 commented on index.html
> +<!DOCTYPE html>
どちらでもよさそう（過去の仕様の名残り？）なので、これはこのままで
https://on-ze.com/blog/1933

2024-08-18 07:47 UTC, claustra01 commented on src/components/Yatai/TargetOverlay.module.css
> +  transition: all 0.1s linear;
理解しました、ありがとうございます

2024-08-18 20:34 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> -	const [score, setScore] = useState<number>(0);
sea10さんのzustandでのscore管理をマージしたので、そのまま消しておきます

2024-08-18 20:34 UTC, K-Kizuku commented on src/pages/shooter/index.tsx
> -	}, [onMessage, uuid, score]);
上に同じ

2024-08-18 23:36 UTC, claustra01 commented
deployし直しのためreopen

2024-08-18 23:56 UTC, claustra01 requested changes

2024-08-18 23:56 UTC, claustra01 commented on src/components/Gallery/index.tsx
> +		resetTargetStatus();
ここでtargetStatusのリセットをしているが、正常な遷移（/result）ではリセットされていないので、ここではなくて（/yatai）の読み込み時にリセットしたい

2024-08-19 00:03 UTC, K-Kizuku commented on src/components/Gallery/index.tsx
> +		resetTargetStatus();
あ、そうか
そうだね

2024-08-19 01:44 UTC, merged